public: RadialResponce(playerid, callback[])
{
    new id;
    sscanf(callback, "i", id);
    switch(id)
    {
        case 0: 
        {
            /* загрузка транспорта  */
        }
        case 1: 
        {
            /* пассивный режим  */
        }
        case 2: 
        {
            /* анимации  */
        }
        case 3: 
        {
            /* документы  */
        }
        case 5: 
        {
            /* лечь спать  */
        }
        case 6: 
        {
            /* доп. действия  */
        }
        case 7: 
        {
            /* удост. развозчика  */
        }
        case 8: 
        {
            /* фитнес навыки  */
        }
        case 9: 
        {
            /* удост. дальнобойщика  */
        }
        case 10: 
        {
            /* статистика дуэлей  */
        }
        case 11: 
        {
            /* Навыки владения оружием */
        }
    }
    return 1;
}